name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '.github/workflows/release.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install VirusTotal CLI
      run: |
        VT_CLI_VERSION="1.0.1"
        # Create bin directory
        mkdir -p $HOME/bin
        
        # Download the binary directly from GitHub releases
        echo "Downloading VirusTotal CLI v${VT_CLI_VERSION}..."
        curl -OL https://github.com/VirusTotal/vt-cli/releases/download/${VT_CLI_VERSION}/Linux64.zip
        unzip Linux64.zip -d $HOME/bin
        
        # Make it executable
        chmod +x $HOME/bin/vt
        
        # Add to PATH for this and subsequent steps
        echo "$HOME/bin" >> $GITHUB_PATH
        export PATH="$HOME/bin:$PATH"
        
        # Verify installation
        ls -la $HOME/bin
        which vt || echo "vt not found in PATH"
        $HOME/bin/vt --version || echo "vt command failed"

    - name: Install test dependencies
      run: task deps:test
      env:
        VT_API_KEY: ${{ secrets.VT_API_KEY }}
        PATH: ${{ env.PATH }}:${{ env.HOME }}/bin

    - name: Build release artifacts
      run: task release
      env:
        VT_API_KEY: ${{ secrets.VT_API_KEY }}
        PATH: ${{ env.PATH }}:${{ env.HOME }}/bin

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      id: bump_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        name: Release v${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          dist/ipcalc-windows-amd64.zip
          dist/ipcalc-windows-amd64.zip.sha256
          dist/ipcalc-linux-amd64.tar.gz
          dist/ipcalc-linux-amd64.tar.gz.sha256
          dist/ipcalc-darwin-amd64.tar.gz
          dist/ipcalc-darwin-amd64.tar.gz.sha256
          dist/ipcalc-darwin-arm64.tar.gz
          dist/ipcalc-darwin-arm64.tar.gz.sha256
          dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}