name: Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '.github/workflows/release.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build release artifacts
      run: task release

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      id: bump_version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        name: Release v${{ steps.bump_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          dist/ipcalc-windows-amd64.zip
          dist/ipcalc-windows-amd64.zip.sha256
          dist/ipcalc-linux-amd64.tar.gz
          dist/ipcalc-linux-amd64.tar.gz.sha256
          dist/ipcalc-darwin-amd64.tar.gz
          dist/ipcalc-darwin-amd64.tar.gz.sha256
          dist/ipcalc-darwin-arm64.tar.gz
          dist/ipcalc-darwin-arm64.tar.gz.sha256
          dist/checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}